### ISSUE TITLE
No info about connected users

### ISSUE THREAD

**Issue by EvilBox** [criteo/ocserv-exporter#1]
Hi! Thank you for your project!
Unfortunately, I get error (in exporter stdout) when the user is connected to ocserv:
`ERRO[0000] Failed to get users details: error while decoding json json: cannot unmarshal number 4.9 MB/sec into Go struct field UsersMessage.TX of type int64`
and I don't see "vpn_user_rx_bytes" block in /metrics page 

I have ocserv 1.2.0 with rx/tx limits. Of course I activated use-occtl parameter. I use this docker image - evilbox/ocserv:1.2.0
```
Limits in ocserv.conf:
rx-data-per-sec = 4900000
tx-data-per-sec = 4900000
```
when I use "occtl --json show users" I get this json (maybe this will help)
```
[
  {
    "ID":  44,
    "Username":  "user_me-xi09",
    "Groupname":  "(none)",
    "State":  "connected",
    "vhost":  "default",
    "Device":  "vpn0",
    "MTU":  "1434",
    "Remote IP":  "37.XXX.XXX.XXX",
    "Location":  "unknown",
    "Local Device IP":  "100.XXX.XXX.XXX",
    "IPv4":  "10.XXX.XXX.XXX",
    "P-t-P IPv4":  "10.XXX.XXX.XXX",
    "User-Agent":  "AnyConnect AppleSSLVPN_Darwin_ARM (iPhone) 5.0.02602",
    "Limit RX":  "4.9 MB/sec",
    "TX":  "4.9 MB/sec",
    "RX":  "12209987",
    "TX":  "574756426",
    "_RX":  "12.2 MB",
    "_TX":  "574.8 MB",
    "Average RX":  "2.0 KB/sec",
    "Average TX":  "93.3 KB/sec",
    "DPD":  "90",
    "KeepAlive":  "32400",
    "Hostname":  "iPhone-User",
    "Connected at":  "2023-08-10 11:03",
    "_Connected at":  " 1h:42m",
    "Full session":  "XXXXXXXXXXIuq4czpcPRGGwOaO0=",
    "Session":  "XXXkJL",
    "TLS ciphersuite":  "(TLS1.3)-(ECDHE-SECP256R1)-(ECDSA-SECP256R1-SHA256)-(AES-256-GC",
    "DTLS cipher":  "(DTLS1.2)-(ECDHE-RSA)-(AES-256-GCM)",
    "DNS":	["100.XXX.XXX.XXX"],
    "NBNS":	[],
    "Split-DNS-Domains":	[],
    "Routes":	[],
    "Routes":  "defaultroute",
    "No-routes":	[],
    "iRoutes":	[],
    "Restricted to routes":  "False",
    "Restricted to ports":	[]
  }
]
```

and I see the same text (4.9 MB/sec)

Can you know how to resolve this error? Thank you so much again!

**Comment by fdomain** [comment]
Hello @EvilBox,

Thanks for raising this issue.
From what I see from your `occtl --json show users` output, it looks like a bug on ocserv side, there are twice the "TX" key (they should be unique), and I believe the first one should be "Limit TX" instead of "TX". So I suspect the JSON unmarshalling process fetches the first TX key, which is not something that could be parsed due to the MB/sec unit.

If you remove your `rx-data-per-sec` and `tx-data-per-sec` limits, could you confirm the exporter works?

In the meantime I'll have a look to the ocserv code, I think it could be quite simple to fix.

**Comment by fdomain** [comment]
I've just proposed this [PR](https://gitlab.com/openconnect/ocserv/-/merge_requests/363) on ocserv to fix this.

**Comment by EvilBox** [comment]
Hi @fdomain, 
> If you remove your rx-data-per-sec and tx-data-per-sec limits, could you confirm the exporter works?

Yep. When I removed rx/tx limits the exporter worked flawlessly 

> From what I see from your occtl --json show users output, it looks like a bug on ocserv side, there are twice the "TX" key (they should be unique), and I believe the first one should be "Limit TX" instead of "TX".

Yes it's true maybe the word "limit" is missing. I read your PR in the official ocesrv repo. Thank you for your contribution. I hope the developer agrees with your PR

**Comment by EvilBox** [comment]
I made ocserv docker image with your fix - https://hub.docker.com/r/evilbox/ocserv (ocserv:1.2.0-1 tag)
now exporter works like a charm
