### ISSUE TITLE
Add "how to install in readme"

### ISSUE THREAD

**Issue by skl256** [criteo/ocserv-exporter#4]
**Describe the solution you'd like**
Add "how to install in readme"

**Additional context**
E.g.

> sudo su
> mkdir /opt/ocserv-exporter && cd /opt/ocserv-exporter
> wget https://github.com/criteo/ocserv-exporter/releases/download/v0.2.1/ocserv-exporter_0.2.1_linux_amd64.tar.gz && tar -xvf ocserv-exporter_0.2.1_linux_amd64.tar.gz && rm ocserv-exporter_0.2.1_linux_amd64.tar.gz
> nano /etc/systemd/system/ocserv-exporter.service

----
[Unit]
Description=OpenConnect Prometheus exporter
Documentation=cat /opt/ocserv-exporter/README.md
After=ocserv.service
[Service]
User=root
Restart=always
RestartSec=15
WorkingDirectory=/opt/ocserv-exporter
ExecStart=/opt/ocserv-exporter/ocserv-exporter --interval 30s --listen 127.0.0.1.3:9100
[Install]
WantedBy=multi-user.target
---

> systemctl enable ocserv-exporter && systemctl start ocserv-exporter

P.S. this it example written in one minute, need to improve

**Comment by fdomain** [comment]
Hi @skl256 ,

Thanks for your issue.
I consider that any user able to install ocserv would have the required knowledge to download and untar the archive, I don't think it's necessary to list all the commands.
Besides, using systemd is not mandatory (it could simply run on a container for instance), so I don't think it's worth to add the systemd service file as well.

**Comment by fdomain** [comment]
I'm closing this ticket, but thank you for your suggestion.
